# Generated by Django 5.1.4 on 2025-01-27 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('hospital_affiliation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CostosEstadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_medication_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_procedure_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_statistics', to='gestion_datos.afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='EstudioProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_id', models.CharField(max_length=20, unique=True)),
                ('study_type', models.CharField(choices=[('ECG', 'Electrocardiograma'), ('RM', 'Resonancia Magnética'), ('TAC', 'Tomografía Axial Computarizada'), ('RX', 'Radiografía')], max_length=3)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compliance_with_guideline', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='gestion_datos.afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(max_length=20, unique=True)),
                ('auditor', models.CharField(max_length=50)),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('audit_result', models.TextField()),
                ('recommendation', models.TextField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='gestion_datos.estudioprocedimiento')),
            ],
        ),
    ]
