# Generated by Django 5.1.4 on 2025-01-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0002_medico_costosestadisticas_estudioprocedimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioprocedimiento',
            name='study_type',
            field=models.CharField(choices=[('ECG', 'Electrocardiograma'), ('RM', 'Resonancia Magnética'), ('TAC', 'Tomografía Axial Computarizada'), ('RX', 'Radiografía'), ('RML', 'Resonancia Magnética Lumbar'), ('RTX', 'Radiografía de Tórax de Rutina'), ('EM', 'Ecografía Mamaria Anual'), ('ECGR', 'Electrocardiograma de Rutina'), ('TCC', 'Tomografía Computada de Cráneo'), ('PSA', 'Test de PSA Sin Síntomas')], max_length=4),
        ),
    ]
