# Generated by Django 5.1.4 on 2025-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0003_alter_estudioprocedimiento_study_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='plan',
            field=models.CharField(default='Básico', max_length=50),
        ),
    ]
