# Generated by Django 5.1.4 on 2025-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0004_afiliado_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudioprocedimiento',
            name='study_type',
        ),
        migrations.AlterField(
            model_name='estudioprocedimiento',
            name='procedure_id',
            field=models.CharField(max_length=30),
        ),
    ]
