# Generated by Django 5.1.4 on 2025-04-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_datos', '0005_remove_estudioprocedimiento_study_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioprocedimiento',
            name='study_type',
            field=models.CharField(default='No especificado', max_length=50),
        ),
        migrations.CreateModel(
            name='LaboratorioProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_id', models.CharField(max_length=20, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_type', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labprocedures', to='gestion_datos.afiliado')),
            ],
        ),
    ]
